### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by chefchansey** [Ditto-money/staking#6]
Add tooltips with the following text to the fields APY, REWARD MULTIPLIER and REWARDS EARNED:

APY

APY is estimated for a new deposit over the next 30 days. The APY metric does not account for gains or losses from holding liquidity tokens, or gains from liquidity mining rewards distributed by the underlying plarform for holding liquidity tokens.

REWARD MULTIPLIER

Deposit liquidity for 14 days to achieve a 3x reward multiplier. The multiplier applies to DITTO rewards only.

REWARDS EARNED

Amount of DITTO and CAKE rewards you will receive on unstaking. Note that unstaking resets your multiplier.

**Comment by kelonye** [comment]
Done.
