### ISSUE TITLE
Display BNB bonus pool share

### ISSUE THREAD

**Issue by chefchansey** [Ditto-money/staking#8]
Displays the user's share in % and projected BNB payout on the dashboard.

### Bonus share display

In the first program, 250 BNB are distributed linearly over 21 days. We display the user’s share of the BNB bonus pool and projected payout at the end of the program. E.g:

-----------------
**Projected bonus share (i)**

1%
2.5 BNB

To receive this reward you must stake until Jan. 25th 2021.

-----------------

**Tooltip:** 

"Your share of the BNB bonus pool and projected payout. Varies depending on your amount of staking shares, staking duration and total amount of tokens staked. Stake more LP tokens for longer to increase your share."

### How to calculate the bonus share

The user’s share is given by userStakingShareSeconds / totalStakingShareSeconds. 

pool_amount = 250  	# total amount of BNB paid out
user_share = userStakingShareSeconds / totalStakingShareSeconds
projected_payout = pool_amount  * user_share
user_share_percentage = user_share * 100

**Comment by chefchansey** [comment]
@vbstreetz I updated the calculation method. Seems like userStakingShareSeconds and totalStakingShareSeconds are available in the JS context so can easily calculate the user's share.

**Comment by kelonye** [comment]
Awesome!
